
/* Table: ALERTA, Owner: SYSDBA */
CREATE TABLE ALERTA 
(
        ID_ALERTA	INTEGER NOT NULL,
        ID_USUARIO	INTEGER NOT NULL,
        ID_DETALLE_PRESUPUESTO	INTEGER,
        ID_OBLIGACION	INTEGER,
        ID_META	INTEGER,
        TIPO_ALERTA	VARCHAR(50),
        TITULO	VARCHAR(100),
        MENSAJE	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        PRIORIDAD	VARCHAR(20),
        FECHA_CREACION	TIMESTAMP NOT NULL,
        VISTA	BOOLEAN,
        FECHA_LEIDA	TIMESTAMP,
        CREADO_POR	VARCHAR(100),
        MODIFICADO_POR	VARCHAR(100),
        CREADO_EN	TIMESTAMP NOT NULL,
        MODIFICADO_EN	TIMESTAMP NOT NULL,
CONSTRAINT PK_ALERTA PRIMARY KEY (ID_ALERTA)
);
ALTER TABLE ALERTA ADD CONSTRAINT FK_ALERTA_DETALLE FOREIGN KEY (ID_DETALLE_PRESUPUESTO) REFERENCES PRESUPUESTO_DETALLE (ID_DETALLE);
ALTER TABLE ALERTA ADD CONSTRAINT FK_ALERTA_META FOREIGN KEY (ID_META) REFERENCES META_AHORRO (ID_META);
ALTER TABLE ALERTA ADD CONSTRAINT FK_ALERTA_OBLIGACION FOREIGN KEY (ID_OBLIGACION) REFERENCES OBLIGACION_FIJA (ID_OBLIGACION);
ALTER TABLE ALERTA ADD CONSTRAINT FK_ALERTA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

/* Triggers only will work for SQL triggers */

CREATE TRIGGER ALERTA_BI FOR ALERTA 
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.id_alerta IS NULL) THEN
    NEW.id_alerta = GEN_ID(gen_alerta_id, 1);
END
 ;

COMMIT WORK ;

/* Meta data descriptions.  This syntax requires InterBase 2020 or higher.  Some tables require ODS18 and higher */

