
/* Table: CATEGORIA, Owner: SYSDBA */
CREATE TABLE CATEGORIA 
(
        ID_CATEGORIA	INTEGER NOT NULL,
        NOMBRE_CATEGORIA	VARCHAR(100) NOT NULL,
        DESCRIPCION	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        TIPO	VARCHAR(20) NOT NULL,
        ICONO	VARCHAR(100),
        COLOR	VARCHAR(20),
        ORDEN_PRESENTACION	INTEGER,
        CREADO_POR	VARCHAR(100),
        MODIFICADO_POR	VARCHAR(100),
        CREADO_EN	TIMESTAMP NOT NULL,
        MODIFICADO_EN	TIMESTAMP NOT NULL,
 PRIMARY KEY (ID_CATEGORIA)
);

/* Meta data descriptions.  This syntax requires InterBase 2020 or higher.  Some tables require ODS18 and higher */

