
/* Table: META_AHORRO, Owner: SYSDBA */
CREATE TABLE META_AHORRO 
(
        ID_META	INTEGER NOT NULL,
        ID_USUARIO	INTEGER NOT NULL,
        ID_SUBCATEGORIA	INTEGER NOT NULL,
        NOMBRE_META	VARCHAR(100) NOT NULL,
        DESCRIPCION	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        MONTO_OBJETIVO	NUMERIC(10, 2) NOT NULL,
        MONTO_ACUMULADO	NUMERIC(10, 2),
        FECHA_INICIO	DATE NOT NULL,
        FECHA_OBJETIVO	DATE NOT NULL,
        PRIORIDAD	VARCHAR(20),
        ESTADO	VARCHAR(20),
        CREADO_POR	VARCHAR(100),
        MODIFICADO_POR	VARCHAR(100),
        CREADO_EN	TIMESTAMP NOT NULL,
        MODIFICADO_EN	TIMESTAMP NOT NULL,
 PRIMARY KEY (ID_META)
);
ALTER TABLE META_AHORRO ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);
ALTER TABLE META_AHORRO ADD FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIA (ID_SUBCATEGORIA);

/* Meta data descriptions.  This syntax requires InterBase 2020 or higher.  Some tables require ODS18 and higher */

