
/* Table: OBLIGACION_FIJA, Owner: SYSDBA */
CREATE TABLE OBLIGACION_FIJA 
(
        ID_OBLIGACION	INTEGER NOT NULL,
        ID_USUARIO	INTEGER NOT NULL,
        ID_SUBCATEGORIA	INTEGER NOT NULL,
        NOMBRE_OBLIGACION	VARCHAR(100) NOT NULL,
        DESCRIPCION	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        MONTO_MENSUAL	NUMERIC(10, 2) NOT NULL,
        DIA_VENCIMIENTO	INTEGER NOT NULL,
        VIGENTE	BOOLEAN,
        FECHA_INICIO	DATE NOT NULL,
        FECHA_FIN	DATE,
        CREADO_POR	VARCHAR(100),
        MODIFICADO_POR	VARCHAR(100),
        CREADO_EN	TIMESTAMP NOT NULL,
        MODIFICADO_EN	TIMESTAMP NOT NULL,
 PRIMARY KEY (ID_OBLIGACION)
);
ALTER TABLE OBLIGACION_FIJA ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);
ALTER TABLE OBLIGACION_FIJA ADD FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIA (ID_SUBCATEGORIA);

/* Meta data descriptions.  This syntax requires InterBase 2020 or higher.  Some tables require ODS18 and higher */

