
/* Table: PRESUPUESTO, Owner: SYSDBA */
CREATE TABLE PRESUPUESTO 
(
        ID_PRESUPUESTO	INTEGER NOT NULL,
        ID_USUARIO	INTEGER NOT NULL,
        NOMBRE_PRESUPUESTO	VARCHAR(100) NOT NULL,
        ANO_INICIO	INTEGER NOT NULL,
        MES_INICIO	INTEGER NOT NULL,
        ANO_FIN	INTEGER NOT NULL,
        MES_FIN	INTEGER NOT NULL,
        TOTAL_INGRESOS_PLANIFICADOS	NUMERIC(10, 2),
        TOTAL_GASTOS_PLANIFICADOS	NUMERIC(10, 2),
        TOTAL_AHORRO_PLANIFICADO	NUMERIC(10, 2),
        FECHA_CREACION	TIMESTAMP NOT NULL,
        ESTADO	VARCHAR(20) NOT NULL,
        CREADO_POR	VARCHAR(100),
        MODIFICADO_POR	VARCHAR(100),
        CREADO_EN	TIMESTAMP NOT NULL,
        MODIFICADO_EN	TIMESTAMP NOT NULL,
 PRIMARY KEY (ID_PRESUPUESTO)
);
ALTER TABLE PRESUPUESTO ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

/* Meta data descriptions.  This syntax requires InterBase 2020 or higher.  Some tables require ODS18 and higher */

