
/* Table: PRESUPUESTO_DETALLE, Owner: SYSDBA */
CREATE TABLE PRESUPUESTO_DETALLE 
(
        ID_DETALLE	INTEGER NOT NULL,
        ID_PRESUPUESTO	INTEGER NOT NULL,
        ID_SUBCATEGORIA	INTEGER NOT NULL,
        MONTO_MENSUAL_ASIGNADO	NUMERIC(10, 2),
        OBSERVACIONES	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        CREADO_POR	VARCHAR(100),
        MODIFICADO_POR	VARCHAR(100),
        CREADO_EN	TIMESTAMP NOT NULL,
        MODIFICADO_EN	TIMESTAMP NOT NULL,
 PRIMARY KEY (ID_DETALLE)
);
ALTER TABLE PRESUPUESTO_DETALLE ADD FOREIGN KEY (ID_PRESUPUESTO) REFERENCES PRESUPUESTO (ID_PRESUPUESTO);
ALTER TABLE PRESUPUESTO_DETALLE ADD FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIA (ID_SUBCATEGORIA);

/* Meta data descriptions.  This syntax requires InterBase 2020 or higher.  Some tables require ODS18 and higher */

