
/* Table: SUBCATEGORIA, Owner: SYSDBA */
CREATE TABLE SUBCATEGORIA 
(
        ID_SUBCATEGORIA	INTEGER NOT NULL,
        ID_CATEGORIA	INTEGER NOT NULL,
        NOMBRE_SUBCATEGORIA	VARCHAR(100) NOT NULL,
        DESCRIPCION	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        ACTIVA	BOOLEAN,
        ES_DEFECTO	BOOLEAN,
        CREADO_POR	VARCHAR(100),
        MODIFICADO_POR	VARCHAR(100),
        CREADO_EN	TIMESTAMP NOT NULL,
        MODIFICADO_EN	TIMESTAMP NOT NULL,
 PRIMARY KEY (ID_SUBCATEGORIA)
);
ALTER TABLE SUBCATEGORIA ADD FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA);

/* Meta data descriptions.  This syntax requires InterBase 2020 or higher.  Some tables require ODS18 and higher */

