
/* Table: TRANSACCION, Owner: SYSDBA */
CREATE TABLE TRANSACCION 
(
        ID_TRANSACCION	INTEGER NOT NULL,
        ID_USUARIO	INTEGER NOT NULL,
        ID_PRESUPUESTO	INTEGER NOT NULL,
        ID_SUBCATEGORIA	INTEGER NOT NULL,
        ID_OBLIGACION	INTEGER,
        TIPO	VARCHAR(20) NOT NULL,
        ANO	INTEGER NOT NULL,
        MES	INTEGER NOT NULL,
        DESCRIPCION	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        MONTO	NUMERIC(10, 2) NOT NULL,
        FECHA	DATE NOT NULL,
        METODO_PAGO	VARCHAR(50),
        NUM_FACTURA	VARCHAR(50),
        OBSERVACIONES	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        FECHA_REGISTRO	TIMESTAMP NOT NULL,
        CREADO_POR	VARCHAR(100),
        MODIFICADO_POR	VARCHAR(100),
        CREADO_EN	TIMESTAMP NOT NULL,
        MODIFICADO_EN	TIMESTAMP NOT NULL,
 PRIMARY KEY (ID_TRANSACCION)
);
ALTER TABLE TRANSACCION ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);
ALTER TABLE TRANSACCION ADD FOREIGN KEY (ID_PRESUPUESTO) REFERENCES PRESUPUESTO (ID_PRESUPUESTO);
ALTER TABLE TRANSACCION ADD FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIA (ID_SUBCATEGORIA);
ALTER TABLE TRANSACCION ADD FOREIGN KEY (ID_OBLIGACION) REFERENCES OBLIGACION_FIJA (ID_OBLIGACION);

/* Meta data descriptions.  This syntax requires InterBase 2020 or higher.  Some tables require ODS18 and higher */

