
/* Table: USUARIO, Owner: SYSDBA */
CREATE TABLE USUARIO 
(
        ID_USUARIO	INTEGER NOT NULL,
        NOMBRE	VARCHAR(100) NOT NULL,
        APELLIDO	VARCHAR(100) NOT NULL,
        CORREO_ELECTRONICO	VARCHAR(150) NOT NULL,
        FECHA_REGISTRO	DATE NOT NULL,
        SALARIO_MENSUAL_BASE	NUMERIC(10, 2) NOT NULL,
        ESTADO	VARCHAR(20) NOT NULL,
        CREADO_POR	VARCHAR(100),
        MODIFICADO_POR	VARCHAR(100),
        CREADO_EN	TIMESTAMP NOT NULL,
        MODIFICADO_EN	TIMESTAMP NOT NULL,
 PRIMARY KEY (ID_USUARIO),
 UNIQUE (CORREO_ELECTRONICO)
);

/* Meta data descriptions.  This syntax requires InterBase 2020 or higher.  Some tables require ODS18 and higher */

